worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    # 1. Definimos nuestros servicios (Nombres de los contenedores Docker)
    upstream frontend_app {
        # Vite expone por defecto el puerto 5173
        server app-frontend:5173; 
    }

    upstream backend_api {
        # Spring Boot expone por defecto el puerto 8080
        server app-backend:8080;
    }

    server {
        # Escuchamos en el puerto 80 estándar
        listen 80;
        server_name localhost;

        # 2. Regla para el Backend: Todo lo que empiece con /api/ va a Spring Boot
        location /api/ {
            proxy_pass http://backend_api;
            
            # Pasamos las cabeceras originales para que Spring Boot sepa la IP real del cliente
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # 3. Regla para el Frontend: Cualquier otra ruta va a React (Vite)
        location / {
            proxy_pass http://frontend_app;
            proxy_set_header Host $host;
            
            # 4. Soporte OBLIGATORIO para WebSockets (Vite HMR)
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
    }
}